apiVersion: app.spacelift.io/v1beta1
kind: Context
metadata:
  name: context-sample
spec:
  spaceName: space-sample
  attachments:
    - { stackName: stack-sample }
  environment:
    - id: foo
      value: bar
      description: "insecure"
  mountedFiles:
    - id: bar
      value: Zm9vCg==